enum ModalOption {
  POST = "POST",
  POST_PREVIEW = "POST_PREVIEW",
  ALBUM = "ALBUM",
  AlBUM_PREVIEW = "ALBUM_PREVIEW",
  AlBUM_DELETE = "ALBUM_DELETE",
  ALBUM_EDIT = "ALBUM_EDIT",
  WISH = "WISH",
  PROFILE = "PROFILE",
  SETTING = "SETTING",
  SEARCH = "SEARCH",
  FILTER = "FILTER",
  WARNING = "WARNING",
  POST_OPTION = "POST_OPTION",
  EDIT_PROFILE_IMG = "EDIT_PROFILE_IMG",
  SHARE = "SHARE",
  USER_SETTING = "USER_SETTING",
  USER_INFO = "USER_INFO",
}

export default ModalOption;
