enum ModalOption {
  POST = "POST",
  ALBUM = "ALBUM",
  PROFILE = "PROFILE",
  SETTING = "SETTING",
  SEARCH = "SEARCH",
  FILTER = "FILTER",
  WARNING = "WARNING",
  POST_OPTION = "POST_OPTION",
  EDIT_PROFILE_IMG = "EDIT_PROFILE_IMG",
  POST_PREVIEW = "POST_PREVIEW",
  SHARE = "SHARE",
  USER_SETTING = "USER_SETTING",
  USER_INFO = "USER_INFO",
}

export default ModalOption;
