enum ModalOption {
  POST = "POST",
  ALBUM = "ALBUM",
  PROFILE = "PROFILE",
  SETTING = "SETTING",
  SEARCH = "SEARCH",
  WARNING = "WARNING",
  POSTOPTION = "POSTOPTION",
  EDITPROFILEIMG = "EDITPROFILEIMG",
  POST_PREVIEW = "POST_PREVIEW",
}

export default ModalOption;
