enum regionOptionType {
  SEOUL = "SEOUL",
  GYEONGGI = "GYEONGGI",
  INCHEON = "INCHEON",
  GANGWON = "GANGWON",
  JEJU = "JEJU",
  DAEJEON = "DAEJEON",
  CHUNGBUK = "CHUNGBUK",
  CHUNGNAM_SEJONG = "CHUNGNAM/SEJONG",
  BUSAN = "BUSAN",
  ULSAN = "ULSAN",
  GYEONGBUK = "GYEONGBUK",
  DAEGU = "DAEGU",
  GYEONGNAM = "GYEONGNAM",
  JEONBUK = "JEONBUK",
  JEONNAM = "JEONNAM",
  GWANGJU = "GWANGJU",
}

export default regionOptionType;
